all_toys = {
    "JP101":{
                "toy_id": "JP101",
                "owner_id": "super_mom492",
                "coordinates": "18.458,77.235",
                "name": "IntelliSkills Jungle Animals Stick Puzzle",
                "description": "18-pc puzzles, 6 animals, suitable for 3+ kids",
                "images": [],
                "weight": "0.28kg",
                "features": [],
                "recommended_age": "3+",
                "dimensions": "12X12X34",
                "brand": "IntelliSkills",
                "available": True,
                "rating": 4.8,
                "review_count": 1
            },
    "JP102": {
        "toy_id": "JP102",
        "owner_id": "super_mom492",
        "coordinates": "19.123,78.456",
        "name": "Creative Blocks Building Set",
        "description": "50-pc blocks, various shapes and colors, suitable for 3+ kids",
        "images": [],
        "weight": "0.45kg",
        "features": [],
        "recommended_age": "3+",
        "dimensions": "20X20X20",
        "brand": "CreativeToys",
        "available": False,
        "rating": 4.7,
        "review_count": 15
    },
    "JP103": {
        "toy_id": "JP103",
        "owner_id": "super_mom492",
        "coordinates": "20.789,79.123",
        "name": "Mini Car Assembly Kit",
        "description": "20-pc assembly kit, build your own cars, suitable for 3+ kids",
        "images": [],
        "weight": "0.35kg",
        "features": [],
        "recommended_age": "3+",
        "dimensions": "15X10X10",
        "brand": "BuildAndPlay",
        "available": True,
        "rating": 4.9,
        "review_count": 7
    },
    "JP104": {
        "toy_id": "JP104",
        "owner_id": "super_mom492",
        "coordinates": "21.345,80.678",
        "name": "Shape Sorting Cube",
        "description": "15-pc shape sorter, various shapes and colors, suitable for 3+ kids",
        "images": [],
        "weight": "0.40kg",
        "features": [],
        "recommended_age": "3+",
        "dimensions": "18X18X18",
        "brand": "SmartyTots",
        "available": False,
        "rating": 4.6,
        "review_count": 12
    }
}